"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# ===========================================
# SECURITY
# ===========================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-yl)7#ipuu-m3irx_0zp46!9dd&v51ug_g^&ox2aon!o5l6)-=)"
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# ===========================================
# APPLICATIONS
# ===========================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'myapp',
]


# ===========================================
# MIDDLEWARE
# ===========================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'myproject.urls'


# ===========================================
# TEMPLATES
# ===========================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'myproject.wsgi.application'


# ===========================================
# DATABASE
# ===========================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ===========================================
# PASSWORD VALIDATION
# ===========================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ===========================================
# INTERNATIONALIZATION
# ===========================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ===========================================
# STATIC FILES
# ===========================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ===========================================
# MEDIA FILES
# ===========================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ===========================================
# FILE UPLOAD
# ===========================================

DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024

FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024


# ===========================================
# DEFAULT PRIMARY KEY
# ===========================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'